In [1]:
lista = [24, 13, 18, 20, 32]

In [2]:
import numpy as np

In [3]:
np.array(lista)

array([24, 13, 18, 20, 32])

In [4]:
na = np.array(lista)

In [5]:
print(na)

[24 13 18 20 32]


In [10]:
lista = [24, 13, 18, 20, 32]
listb = [15, 16, 18, 19, 33]

In [11]:
nb = np.array([lista, listb])

In [12]:
print(nb)

[[24 13 18 20 32]
 [15 16 18 19 33]]


In [13]:
nb.ndim

2

In [14]:
na.ndim

1

In [15]:
nb.shape

(2, 5)

In [16]:
na.shape

(5,)

In [17]:
nb.size

10

In [19]:
nc = np.zeros(7)

In [20]:
print(nc)

[0. 0. 0. 0. 0. 0. 0.]


In [21]:
nd = np.zeros(shape=(2,3))

In [22]:
print(nd)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
ne = np.ones(shape=(3,3))

In [24]:
print(ne)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
lista = [24, 13, 18, 20]
listb = [15, 16, 18, 19]
listc = [88, 71, 20, 24]

nb = np.array([lista, listb, listc])

In [26]:
print(nb)

[[24 13 18 20]
 [15 16 18 19]
 [88 71 20 24]]


In [27]:
nb.reshape((6,2))

array([[24, 13],
       [18, 20],
       [15, 16],
       [18, 19],
       [88, 71],
       [20, 24]])